### ISSUE TITLE
Publish TypeScript types

### ISSUE THREAD

**Issue by moltar** [KevinWang15/web-marker#1]
Can you please publish this package with types?

Please see: https://cameronnokes.com/blog/the-30-second-guide-to-publishing-a-typescript-package-to-npm/

**Comment by moltar** [comment]
Right now, these are the contents of the package:

```
❯ tree node_modules/@notelix/web-marker
node_modules/@notelix/web-marker
├── LICENSE
├── README.md
├── build
│   ├── logo.svg
│   ├── web-marker.js
│   └── web-marker.js.map
├── design
│   └── logo
│       ├── FullColor_1280x1024.eps
│       ├── FullColor_1280x1024.pdf
│       └── FullColor_1280x1024.svg
├── package.json
└── tsconfig.json
```

Also `design/*` can probably be added to `.npmignore`

**Comment by KevinWang15** [comment]
I'd like to work on it.
In the mean time, PRs are welcome

**Comment by KevinWang15** [comment]
I have added typescript support too, in https://github.com/notelix/web-marker/commit/d81809324c13ebb4b2f7194d92f2d9506cf36a09

```
yarn add @notelix/web-marker@^0.2.0
```

**Comment by moltar** [comment]
Thank you 🙏🏼 Will test next week.
