### ISSUE TITLE
uuid dependency

### ISSUE THREAD

**Issue by moltar** [KevinWang15/web-marker#2]
README says:

> no dependency

Yet there is `uuid`:

https://github.com/notelix/web-marker/blob/538e6ed42b9a6a398f1b9bb0d0fac1ab5955ab9f/package.json#L14-L16

Not a big deal either way. Just wanted to point it out.

**Comment by KevinWang15** [comment]
😃 Maybe I should state it as "almost zero dependency"

**Comment by KevinWang15** [comment]
So I decided to remove the uuid dependency instead.. 

https://github.com/notelix/web-marker/commit/5289273e3393cc8e34b8aa065f580d5847c5fe70
