### ISSUE TITLE
Bug: highlighting inside an existing highlight does not work well

### ISSUE THREAD

**Issue by moltar** [KevinWang15/web-marker#26]
Highlighting inside an existing highlight removes the original highlight and narrows it to the new highlight.

There can be a use case for highlight _inside_ a highlight, and IMO this should be handled gracefully.

For example, I might want to highlight in red, inside a yellow highlight.

Demo:

![screenshot-20210929T135427-3wnxARlg](https://user-images.githubusercontent.com/491247/135218079-d73fdcd6-9798-4768-8fe1-74a268f257bb.gif)

**Comment by KevinWang15** [comment]
Hi, actually this should work fine:

![2021-09-29_23-34-24 (1)](https://user-images.githubusercontent.com/10173472/135301566-1ddf2758-45cb-49ac-95e9-f73b408076a3.gif)

You can see code for this sample here: https://github.com/notelix/notelix

**Comment by KevinWang15** [comment]
If you copy-pasted the DEMO code, it's probably because existing highlights were removed in `onHighlightClick`.

```javascript
        onHighlightClick: (context, element) => {
            marker.unpaint(context.serializedRange);
        },
```

Try removing this line.
