### ISSUE TITLE
Use instanceof instead of type casting

### ISSUE THREAD

**Issue by moltar** [KevinWang15/web-marker#3]
You can type guard using `instanceof` like this:

```ts
clickListener = ({ target }: Event) => {

  if (target instanceof Element) {
    // target is now guaranteed to be of type Element and has getAttribute method available
  }

        const id = (<HTMLElement>e.target)?.getAttribute(AttributeNameHighlightId);
        if (id && this.eventHandler.onHighlightClick) {
            this.eventHandler.onHighlightClick(this.buildContext(id), <HTMLElement>e.target)
        }
    };
```

https://github.com/notelix/web-marker/blob/538e6ed42b9a6a398f1b9bb0d0fac1ab5955ab9f/src/lib/classes/Marker.ts#L229-L236

**Comment by KevinWang15** [comment]
Yes, I think returning if it is not instanceof HTMLElement is a good idea, as it can prevent runtime errors.
In reality, have you ever encountered situations where e.target is not an HTMLElement (and threw an Exception)?

**Comment by moltar** [comment]
>  In reality, have you ever encountered situations where e.target is not an HTMLElement (and threw an Exception)?

I don't remember tbh.

But I like defensive programming, so I try to cover all edge cases, even if they are rare or impossible.

I am guessing the `target` is not of type `HTMLElement` by default, because there could be other values?

**Comment by moltar** [comment]
Here are all of the possible values:

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget

**Comment by KevinWang15** [comment]
Thanks, I have fixed it in https://github.com/notelix/web-marker/commit/95de5f38d627362c4d0ea7c9ce1c887ca587940b
