### ISSUE TITLE
Switch to standards-compliant UUID

### ISSUE THREAD

**Issue by dit7ya** [KevinWang15/web-marker#4]
Hi, 

Absolutely fantastic job with this library - thank you so much.

Would it be possible to switch to the RFC compliant UUID format for the `makeid` util function? This allows better direct compatibility with most databases. A library like https://github.com/uuidjs/uuid can be used.

I can do a pull request if you think this is a good idea.

**Comment by KevinWang15** [comment]
@dit7ya Thank you! Yes, good idea, I'd love to have a PR.

**Comment by KevinWang15** [comment]
P.S. I'm building a chrome extension (backend included) with notelix/web-marker these days, you might find it helpful: https://github.com/notelix/notelix
