### ISSUE TITLE
重复出错

### ISSUE THREAD

**Issue by liuyuchuans** [KevinWang15/web-marker#52]
![image](https://user-images.githubusercontent.com/37658672/158529402-26e7afd9-3e40-42ff-8490-08afdcbedb41.png)
就像这样 我明明标记的后面的某一段问题 但是显示标记的却是第一段
![image](https://user-images.githubusercontent.com/37658672/158529885-b44b7e43-ab76-4a58-96a4-d5a34e685ef4.png)

**Comment by KevinWang15** [comment]
是的，这是已知问题，因为序列化range的方式是使用textBefore + text + textAfter，所以有大段重复文字的时候会有这样的问题

有其他的序列化方式，例如 https://github.com/alienzhou/web-highlighter 使用的是offset的方式来序列化，但这种方式仅适用于永远不变的静态文本，当文本发生变化时会反序列化出错误的结果

一般来讲web-marker所采用的textBefore + text + textAfter方式在实际使用中效果更好，也是weava、diigo等著名软件使用的方式。行业内暂时没有完美的解决方式
