### ISSUE TITLE
when highlight in iframe, serializeRange always returns null.

### ISSUE THREAD

**Issue by lee88688** [KevinWang15/web-marker#57]
when I use this library in top window and highlight some element in iframe, I find serializeRange always returns null. when I look source code, I find `serializeRange` function directly uses `document`. I think this may be the reason.
https://github.com/notelix/web-marker/blob/ed0b7cab69944774e7ebc19ff0a6734d374834d0/src/lib/classes/Marker.ts#L170

**Comment by KevinWang15** [comment]
Indeed, I never tested this library with `iframe`. Is it even possible to highlight elements in an `iframe`? (not sure..)
If you can figure out ways to fix this issue then PRs are always welcome. Or I can take a look later.
